export const AppActionTypes = {
    GET_VERIFICATION_CODE: 'GET_VERIFICATION_CODE',
    CODE_SENT: 'CODE_SENT',
    CHECK_VERIFICATION_CODE: 'CHECK_VERIFICATION_CODE',
    PHONE_VERIFIED: 'PHONE_VERIFIED',
    RESET_VERIFY: 'RESET_VERIFY',
}